module.exports = [
  { name: "Mumbai", state: "Maharashtra" },
  { name: "Delhi", state: "Delhi" },
  { name: "Bangalore", state: "Karnataka" },
  { name: "Ahmedabad", state: "Gujarat" },
  { name: "Hyderabad", state: "Telangana" },
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Kolkata", state: "West Bengal" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Surat", state: "Gujarat" },
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Kanpur", state: "Uttar Pradesh" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Thane", state: "Maharashtra" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Pimpri-Chinchwad", state: "Maharashtra" },
  { name: "Patna", state: "Bihar" },
  { name: "Vadodara", state: "Gujarat" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Ludhiana", state: "Punjab" },
  { name: "Agra", state: "Uttar Pradesh" },
  { name: "Nashik", state: "Maharashtra" },
  { name: "Faridabad", state: "Haryana" },
  { name: "Meerut", state: "Uttar Pradesh" },
  { name: "Rajkot", state: "Gujarat" },
  { name: "Kalyan-Dombivli", state: "Maharashtra" },
  { name: "Vasai-Virar", state: "Maharashtra" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Srinagar", state: "Jammu and Kashmir" },
  { name: "Aurangabad", state: "Maharashtra" },
  { name: "Dhanbad", state: "Jharkhand" },
  { name: "Amritsar", state: "Punjab" },
  { name: "Navi Mumbai", state: "Maharashtra" },
  { name: "Allahabad", state: "Uttar Pradesh" },
  { name: "Ranchi", state: "Jharkhand" },
  { name: "Howrah", state: "West Bengal" },
  { name: "Coimbatore", state: "Tamil Nadu" },
  { name: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Gwalior", state: "Madhya Pradesh" },
  { name: "Vijayawada", state: "Andhra Pradesh" },
  { name: "Jodhpur", state: "Rajasthan" },
  { name: "Madurai", state: "Tamil Nadu" },
  { name: "Raipur", state: "Chhattisgarh" },
  { name: "Kota", state: "Rajasthan" },
  { name: "Guwahati", state: "Assam" },
  { name: "Chandigarh", state: "Chandigarh" },
  { name: "Solapur", state: "Maharashtra" },
  { name: "Hubballi-Dharwad", state: "Karnataka" },
  { name: "Bareilly", state: "Uttar Pradesh" },
  { name: "Moradabad", state: "Uttar Pradesh" },
  { name: "Mysore", state: "Karnataka" },
  { name: "Gurgaon", state: "Haryana" },
  { name: "Aligarh", state: "Uttar Pradesh" },
  { name: "Jalandhar", state: "Punjab" },
  { name: "Tiruchirappalli", state: "Tamil Nadu" },
  { name: "Bhubaneswar", state: "Odisha" },
  { name: "Salem", state: "Tamil Nadu" },
  { name: "Mira-Bhayandar", state: "Maharashtra" },
  { name: "Warangal", state: "Telangana" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Bhiwandi", state: "Maharashtra" },
  { name: "Saharanpur", state: "Uttar Pradesh" },
  { name: "Gorakhpur", state: "Uttar Pradesh" },
  { name: "Bikaner", state: "Rajasthan" },
  { name: "Amravati", state: "Maharashtra" },
  { name: "Noida", state: "Uttar Pradesh" },
  { name: "Jamshedpur", state: "Jharkhand" },
  { name: "Bhilai", state: "Chhattisgarh" },
  { name: "Cuttack", state: "Odisha" },
  { name: "Firozabad", state: "Uttar Pradesh" },
  { name: "Kochi", state: "Kerala" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Bhavnagar", state: "Gujarat" },
  { name: "Dehradun", state: "Uttarakhand" },
  { name: "Durgapur", state: "West Bengal" },
  { name: "Asansol", state: "West Bengal" },
  { name: "Rourkela", state: "Odisha" },
  { name: "Nanded", state: "Maharashtra" },
  { name: "Kolhapur", state: "Maharashtra" },
  { name: "Ajmer", state: "Rajasthan" },
  { name: "Akola", state: "Maharashtra" },
  { name: "Gulbarga", state: "Karnataka" },
  { name: "Jamnagar", state: "Gujarat" },
  { name: "Ujjain", state: "Madhya Pradesh" },
  { name: "Loni", state: "Uttar Pradesh" },
  { name: "Siliguri", state: "West Bengal" },
  { name: "Jhansi", state: "Uttar Pradesh" },
  { name: "Ulhasnagar", state: "Maharashtra" },
  { name: "Jammu", state: "Jammu and Kashmir" },
  { name: "Sangli-Miraj & Kupwad", state: "Maharashtra" },
  { name: "Mangalore", state: "Karnataka" },
  { name: "Erode", state: "Tamil Nadu" },
  { name: "Belgaum", state: "Karnataka" },
  { name: "Ambattur", state: "Tamil Nadu" },
  { name: "Tirunelveli", state: "Tamil Nadu" },
  { name: "Malegaon", state: "Maharashtra" },
  { name: "Gaya", state: "Bihar" },
  { name: "Jalgaon", state: "Maharashtra" },
  { name: "Udaipur", state: "Rajasthan" },
  { name: "Maheshtala", state: "West Bengal" },
  { name: "Tirupur", state: "Tamil Nadu" },
  { name: "Davanagere", state: "Karnataka" },
  { name: "Kozhikode", state: "Kerala" },
  { name: "Kurnool", state: "Andhra Pradesh" },
  { name: "Rajpur Sonarpur", state: "West Bengal" },
  { name: "Bokaro Steel City", state: "Jharkhand" },
  { name: "South Dumdum", state: "West Bengal" },
  { name: "Bellary", state: "Karnataka" },
  { name: "Patiala", state: "Punjab" },
  { name: "Gopalpur", state: "West Bengal" },
  { name: "Agartala", state: "Tripura" },
  { name: "Bhagalpur", state: "Bihar" },
  { name: "Muzaffarnagar", state: "Uttar Pradesh" },
  { name: "Bhatpara", state: "West Bengal" },
  { name: "Panihati", state: "West Bengal" },
  { name: "Latur", state: "Maharashtra" },
  { name: "Dhule", state: "Maharashtra" },
  { name: "Rohtak", state: "Haryana" },
  { name: "Sagar", state: "Madhya Pradesh" },
  { name: "Korba", state: "Chhattisgarh" },
  { name: "Bhilwara", state: "Rajasthan" },
  { name: "Berhampur", state: "Odisha" },
  { name: "Muzaffarpur", state: "Bihar" },
  { name: "Ahmednagar", state: "Maharashtra" },
  { name: "Mathura", state: "Uttar Pradesh" },
  { name: "Kollam", state: "Kerala" },
  { name: "Avadi", state: "Tamil Nadu" },
  { name: "Kadapa", state: "Andhra Pradesh" },
  { name: "Kamarhati", state: "West Bengal" },
  { name: "Sambalpur", state: "Odisha" },
  { name: "Bilaspur", state: "Chhattisgarh" },
  { name: "Shahjahanpur", state: "Uttar Pradesh" },
  { name: "Satara", state: "Maharashtra" },
  { name: "Bijapur", state: "Karnataka" },
  { name: "Rampur", state: "Uttar Pradesh" },
  { name: "Shimoga", state: "Karnataka" },
  { name: "Chandrapur", state: "Maharashtra" },
  { name: "Junagadh", state: "Gujarat" },
  { name: "Thrissur", state: "Kerala" },
  { name: "Alwar", state: "Rajasthan" },
  { name: "Bardhaman", state: "West Bengal" },
  { name: "Kulti", state: "West Bengal" },
  { name: "Kakinada", state: "Andhra Pradesh" },
  { name: "Nizamabad", state: "Telangana" },
  { name: "Parbhani", state: "Maharashtra" },
  { name: "Tumkur", state: "Karnataka" },
  { name: "Khammam", state: "Telangana" },
  { name: "Uzhavarkarai", state: "Puducherry" },
  { name: "Bihar Sharif", state: "Bihar" },
  { name: "Panipat", state: "Haryana" },
  { name: "Darbhanga", state: "Bihar" },
  { name: "Bally", state: "West Bengal" },
  { name: "Aizawl", state: "Mizoram" },
  { name: "Dewas", state: "Madhya Pradesh" },
  { name: "Ichalkaranji", state: "Maharashtra" },
  { name: "Karnal", state: "Haryana" },
  { name: "Bathinda", state: "Punjab" },
  { name: "Jalna", state: "Maharashtra" },
  { name: "Eluru", state: "Andhra Pradesh" },
  { name: "Barasat", state: "West Bengal" },
  { name: "Kirari Suleman Nagar", state: "Delhi" },
  { name: "Purnia", state: "Bihar" },
  { name: "Satna", state: "Madhya Pradesh" },
  { name: "Mau", state: "Uttar Pradesh" },
  { name: "Sonipat", state: "Haryana" },
  { name: "Farrukhabad", state: "Uttar Pradesh" },
  { name: "Rourkela", state: "Odisha" },
  { name: "Durg", state: "Chhattisgarh" },
  { name: "Imphal", state: "Manipur" },
  { name: "Ratlam", state: "Madhya Pradesh" },
  { name: "Hapur", state: "Uttar Pradesh" },
  { name: "Arrah", state: "Bihar" },
  { name: "Anantapur", state: "Andhra Pradesh" },
  { name: "Karimnagar", state: "Telangana" },
  { name: "Etawah", state: "Uttar Pradesh" },
  { name: "Ambernath", state: "Maharashtra" },
  { name: "North Dumdum", state: "West Bengal" },
  { name: "Bharatpur", state: "Rajasthan" },
  { name: "Begusarai", state: "Bihar" },
  { name: "New Delhi", state: "Delhi" },
  { name: "Gandhidham", state: "Gujarat" },
  { name: "Baranagar", state: "West Bengal" },
  { name: "Tiruvottiyur", state: "Tamil Nadu" },
  { name: "Puducherry", state: "Puducherry" },
  { name: "Sikar", state: "Rajasthan" },
  { name: "Thoothukudi", state: "Tamil Nadu" },
  { name: "Rewa", state: "Madhya Pradesh" },
  { name: "Mirzapur", state: "Uttar Pradesh" },
  { name: "Raichur", state: "Karnataka" },
  { name: "Pali", state: "Rajasthan" },
  { name: "Ramagundam", state: "Telangana" },
  { name: "Silchar", state: "Assam" },
  { name: "Haridwar", state: "Uttarakhand" },
  { name: "Vijayanagaram", state: "Andhra Pradesh" },
  { name: "Tenali", state: "Andhra Pradesh" },
  { name: "Nagercoil", state: "Tamil Nadu" },
  { name: "Sri Ganganagar", state: "Rajasthan" },
  { name: "Karur", state: "Tamil Nadu" },
  { name: "Uluberia", state: "West Bengal" },
  { name: "Jhunjhunu", state: "Rajasthan" },
  { name: "Bhind", state: "Madhya Pradesh" },
  { name: "Morena", state: "Madhya Pradesh" },
  { name: "Haldwani", state: "Uttarakhand" },
  { name: "Khanna", state: "Punjab" },
  { name: "Sangrur", state: "Punjab" },
  { name: "Barnala", state: "Punjab" },
  { name: "Muktsar", state: "Punjab" },
  { name: "Fazilka", state: "Punjab" },
  { name: "Mansa", state: "Punjab" },
  { name: "Firozpur", state: "Punjab" },
  { name: "Rupnagar", state: "Punjab" },
  { name: "Amreli", state: "Gujarat" },
  { name: "Anand", state: "Gujarat" },
  { name: "Navsari", state: "Gujarat" },
  { name: "Valsad", state: "Gujarat" },
  { name: "Bharuch", state: "Gujarat" },
  { name: "Gandhinagar", state: "Gujarat" },
  { name: "Porbandar", state: "Gujarat" },
  { name: "Vapi", state: "Gujarat" },
  { name: "Godhra", state: "Gujarat" },
  { name: "Mehsana", state: "Gujarat" },
  { name: "Patan", state: "Gujarat" },
  { name: "Surendranagar", state: "Gujarat" },
  { name: "Morbi", state: "Gujarat" },
  { name: "Himatnagar", state: "Gujarat" },
  { name: "Veraval", state: "Gujarat" },
  { name: "Siddhpur", state: "Gujarat" },
  { name: "Unjha", state: "Gujarat" },
  { name: "Visnagar", state: "Gujarat" },
  { name: "Disa", state: "Gujarat" },
  { name: "Palanpur", state: "Gujarat" },
  { name: "Modasa", state: "Gujarat" },
  { name: "Lunawada", state: "Gujarat" },
  { name: "Dahod", state: "Gujarat" },
  { name: "Halol", state: "Gujarat" },
  { name: "Kalol", state: "Gujarat" },
  { name: "Kadi", state: "Gujarat" },
  { name: "Chhatral", state: "Gujarat" },
  { name: "Nadiad", state: "Gujarat" },
  { name: "Vadtal", state: "Gujarat" },
  { name: "Borsad", state: "Gujarat" },
  { name: "Petlad", state: "Gujarat" },
  { name: "Khambhat", state: "Gujarat" },
  { name: "Dholka", state: "Gujarat" },
  { name: "Dhandhuka", state: "Gujarat" },
  { name: "Viramgam", state: "Gujarat" },
  { name: "Sanand", state: "Gujarat" },
  { name: "Bavla", state: "Gujarat" },
  { name: "Padra", state: "Gujarat" },
  { name: "Karjan", state: "Gujarat" },
  { name: "Dabhoi", state: "Gujarat" },
  { name: "Vyara", state: "Gujarat" },
  { name: "Songadh", state: "Gujarat" },
  { name: "Ahwa", state: "Gujarat" },
  { name: "Saputara", state: "Gujarat" },
  { name: "Waghai", state: "Gujarat" },
  { name: "Billimora", state: "Gujarat" },
  { name: "Chikhli", state: "Gujarat" },
  { name: "Gandevi", state: "Gujarat" },
  { name: "Vansda", state: "Gujarat" },
  { name: "Dharampur", state: "Gujarat" },
  { name: "Umbergaon", state: "Gujarat" },
  { name: "Pardi", state: "Gujarat" },
  { name: "Ankleshwar", state: "Gujarat" },
  { name: "Jambusar", state: "Gujarat" },
  { name: "Amod", state: "Gujarat" },
  { name: "Hansot", state: "Gujarat" },
  { name: "Valia", state: "Gujarat" },
  { name: "Zagadia", state: "Gujarat" },
  { name: "Netrang", state: "Gujarat" },
  { name: "Rajpipla", state: "Gujarat" },
  { name: "Dediyapada", state: "Gujarat" },
  { name: "Sagbara", state: "Gujarat" },
  { name: "Nandod", state: "Gujarat" },
  { name: "Tilakwada", state: "Gujarat" },
  { name: "Kavant", state: "Gujarat" },
  { name: "Chhotaudepur", state: "Gujarat" },
  { name: "Jetpur Pavi", state: "Gujarat" },
  { name: "Sankheda", state: "Gujarat" },
  { name: "Bodeli", state: "Gujarat" },
  { name: "Nasvadi", state: "Gujarat" },
  { name: "Alirajpur", state: "Madhya Pradesh" },
  { name: "Jhabua", state: "Madhya Pradesh" },
  { name: "Dhar", state: "Madhya Pradesh" },
  { name: "Barwani", state: "Madhya Pradesh" },
  { name: "Khargone", state: "Madhya Pradesh" },
  { name: "Khandwa", state: "Madhya Pradesh" },
  { name: "Burhanpur", state: "Madhya Pradesh" },
  { name: "Harda", state: "Madhya Pradesh" },
  { name: "Betul", state: "Madhya Pradesh" },
  { name: "Hoshangabad", state: "Madhya Pradesh" },
  { name: "Sehore", state: "Madhya Pradesh" },
  { name: "Raisen", state: "Madhya Pradesh" },
  { name: "Vidisha", state: "Madhya Pradesh" },
  { name: "Guna", state: "Madhya Pradesh" },
  { name: "Ashoknagar", state: "Madhya Pradesh" },
  { name: "Shivpuri", state: "Madhya Pradesh" },
  { name: "Sheopur", state: "Madhya Pradesh" },
  { name: "Datia", state: "Madhya Pradesh" },
  { name: "Tikamgarh", state: "Madhya Pradesh" },
  { name: "Niwari", state: "Madhya Pradesh" },
  { name: "Chhatarpur", state: "Madhya Pradesh" },
  { name: "Panna", state: "Madhya Pradesh" },
  { name: "Damoh", state: "Madhya Pradesh" },
  { name: "Katni", state: "Madhya Pradesh" },
  { name: "Mandla", state: "Madhya Pradesh" },
  { name: "Dindori", state: "Madhya Pradesh" },
  { name: "Seoni", state: "Madhya Pradesh" },
  { name: "Chhindwara", state: "Madhya Pradesh" },
  { name: "Narsinghpur", state: "Madhya Pradesh" },
  { name: "Balaghat", state: "Madhya Pradesh" },
  { name: "Shahdol", state: "Madhya Pradesh" },
  { name: "Umaria", state: "Madhya Pradesh" },
  { name: "Anuppur", state: "Madhya Pradesh" },
  { name: "Sidhi", state: "Madhya Pradesh" },
  { name: "Singrauli", state: "Madhya Pradesh" },
  { name: "Maihar", state: "Madhya Pradesh" },
  { name: "Chitra", state: "Jharkhand" },
  { name: "Dumka", state: "Jharkhand" },
  { name: "Deoghar", state: "Jharkhand" },
  { name: "Godda", state: "Jharkhand" },
  { name: "Sahibganj", state: "Jharkhand" },
  { name: "Pakur", state: "Jharkhand" },
  { name: "Jamtara", state: "Jharkhand" },
  { name: "Giridih", state: "Jharkhand" },
  { name: "Koderma", state: "Jharkhand" },
  { name: "Hazaribagh", state: "Jharkhand" },
  { name: "Ramgarh", state: "Jharkhand" },
  { name: "Chatra", state: "Jharkhand" },
  { name: "Palamu", state: "Jharkhand" },
  { name: "Garhwa", state: "Jharkhand" },
  { name: "Latehar", state: "Jharkhand" },
  { name: "Lohardaga", state: "Jharkhand" },
  { name: "Gumla", state: "Jharkhand" },
  { name: "Simdega", state: "Jharkhand" },
  { name: "Khunti", state: "Jharkhand" },
  { name: "Purbi Singhbhum", state: "Jharkhand" },
  { name: "Paschimi Singhbhum", state: "Jharkhand" },
  { name: "Seraikela Kharsawan", state: "Jharkhand" },
  { name: "Shimla", state: "Himachal Pradesh" },
  { name: "Manali", state: "Himachal Pradesh" },
  { name: "Dharamshala", state: "Himachal Pradesh" },
  { name: "Kullu", state: "Himachal Pradesh" },
  { name: "Mandi", state: "Himachal Pradesh" },
  { name: "Solan", state: "Himachal Pradesh" },
  { name: "Hamirpur", state: "Himachal Pradesh" },
  { name: "Una", state: "Himachal Pradesh" },
  { name: "Kangra", state: "Himachal Pradesh" },
  { name: "Chamba", state: "Himachal Pradesh" },
  { name: "Kinnaur", state: "Himachal Pradesh" },
  { name: "Lahaul and Spiti", state: "Himachal Pradesh" },
  { name: "Panjim", state: "Goa" },
  { name: "Margao", state: "Goa" },
  { name: "Vasco da Gama", state: "Goa" },
  { name: "Mapusa", state: "Goa" },
  { name: "Ponda", state: "Goa" },
  { name: "Bicholim", state: "Goa" },
  { name: "Curchorem", state: "Goa" },
  { name: "Valpoi", state: "Goa" },
  { name: "Sanquelim", state: "Goa" },
  { name: "Canacona", state: "Goa" },
  { name: "Quepem", state: "Goa" },
  { name: "Sanguem", state: "Goa" },
  { name: "Pernem", state: "Goa" },
  { name: "Itanagar", state: "Arunachal Pradesh" },
  { name: "Tawang", state: "Arunachal Pradesh" },
  { name: "Ziro", state: "Arunachal Pradesh" },
  { name: "Pasighat", state: "Arunachal Pradesh" },
  { name: "Roing", state: "Arunachal Pradesh" },
  { name: "Tezu", state: "Arunachal Pradesh" },
  { name: "Bomdila", state: "Arunachal Pradesh" },
  { name: "Aalo", state: "Arunachal Pradesh" },
  { name: "Daporijo", state: "Arunachal Pradesh" },
  { name: "Seppa", state: "Arunachal Pradesh" },
  { name: "Khonsa", state: "Arunachal Pradesh" },
  { name: "Changlang", state: "Arunachal Pradesh" },
  { name: "Yingkiong", state: "Arunachal Pradesh" },
  { name: "Anini", state: "Arunachal Pradesh" },
  { name: "Kurung Kumey", state: "Arunachal Pradesh" },
  { name: "Anjaw", state: "Arunachal Pradesh" },
  { name: "Longding", state: "Arunachal Pradesh" },
  { name: "Namsai", state: "Arunachal Pradesh" },
  { name: "Kra Daadi", state: "Arunachal Pradesh" },
  { name: "Siang", state: "Arunachal Pradesh" },
  { name: "Lower Siang", state: "Arunachal Pradesh" },
  { name: "Kamle", state: "Arunachal Pradesh" },
  { name: "Pakke Kessang", state: "Arunachal Pradesh" },
  { name: "Lepa Rada", state: "Arunachal Pradesh" },
  { name: "Shi Yomi", state: "Arunachal Pradesh" },
  { name: "Gangtok", state: "Sikkim" },
  { name: "Pelling", state: "Sikkim" },
  { name: "Lachung", state: "Sikkim" },
  { name: "Lachen", state: "Sikkim" },
  { name: "Namchi", state: "Sikkim" },
  { name: "Gyalshing", state: "Sikkim" },
  { name: "Mangan", state: "Sikkim" },
  { name: "Ravangla", state: "Sikkim" },
  { name: "Kohima", state: "Nagaland" },
  { name: "Dimapur", state: "Nagaland" },
  { name: "Mokokchung", state: "Nagaland" },
  { name: "Tuensang", state: "Nagaland" },
  { name: "Mon", state: "Nagaland" },
  { name: "Wokha", state: "Nagaland" },
  { name: "Zunheboto", state: "Nagaland" },
  { name: "Phek", state: "Nagaland" },
  { name: "Kiphire", state: "Nagaland" },
  { name: "Longleng", state: "Nagaland" },
  { name: "Peren", state: "Nagaland" },
  { name: "Noklak", state: "Nagaland" },
  { name: "Shillong", state: "Meghalaya" },
  { name: "Tura", state: "Meghalaya" },
  { name: "Jowai", state: "Meghalaya" },
  { name: "Nongpoh", state: "Meghalaya" },
  { name: "Williamnagar", state: "Meghalaya" },
  { name: "Baghmara", state: "Meghalaya" },
  { name: "Nongstoin", state: "Meghalaya" },
  { name: "Resubelpara", state: "Meghalaya" },
  { name: "Mawkyrwat", state: "Meghalaya" },
  { name: "Ampati", state: "Meghalaya" },
  { name: "Khliehriat", state: "Meghalaya" },
  { name: "Cherrapunji", state: "Meghalaya" },
  { name: "Mairang", state: "Meghalaya" },
  { name: "Silvassa", state: "Dadra and Nagar Haveli" },
  { name: "Kavaratti", state: "Lakshadweep" },
  { name: "Agatti", state: "Lakshadweep" },
  { name: "Minicoy", state: "Lakshadweep" },
  { name: "Amini", state: "Lakshadweep" },
  { name: "Andrott", state: "Lakshadweep" },
  { name: "Bitra", state: "Lakshadweep" },
  { name: "Chetlat", state: "Lakshadweep" },
  { name: "Kadmat", state: "Lakshadweep" },
  { name: "Kalpeni", state: "Lakshadweep" },
  { name: "Kiltan", state: "Lakshadweep" },
  { name: "Port Blair", state: "Andaman and Nicobar Islands" },
  { name: "Diglipur", state: "Andaman and Nicobar Islands" },
  { name: "Mayabunder", state: "Andaman and Nicobar Islands" },
  { name: "Rangat", state: "Andaman and Nicobar Islands" },
  { name: "Havelock", state: "Andaman and Nicobar Islands" },
  { name: "Neil Island", state: "Andaman and Nicobar Islands" },
  { name: "Car Nicobar", state: "Andaman and Nicobar Islands" },
  { name: "Campbell Bay", state: "Andaman and Nicobar Islands" },
  { name: "Nancowry", state: "Andaman and Nicobar Islands" },
  { name: "Little Andaman", state: "Andaman and Nicobar Islands" }
];
